export const allProducts = [
    { 
      image: "assets/images/p6.png", 
      name: "GP11 Shooter USB Gamepad", 
      price: "$660", 
      star: 3, 
      totalRating: 350, 
      discount: 'New', 
      likedProduct: false,
      description: "A high-quality gamepad with excellent responsiveness and a comfortable grip.",
      size: "Medium",
      brand: "Brand Name",
      color: "Black",
      connectivity: "Wired",
      compatibility: "Compatible with PC, Xbox, and PlayStation",
      warranty: "1-year warranty",
      dimensions: "10 x 5 x 2 inches",
      weight: "200 grams"
    },
    { 
      image: "assets/images/p10.png", 
      name: "Quilted Satin Jacket", 
      price: "$350", 
      actualPrice: "$300", 
      star: 4, 
      totalRating: 66, 
      discount: '10%', 
      likedProduct: false,
      description: "Stay stylish and cozy with this quilted satin jacket. Perfect for cool evenings and casual outings.",
      size: "Large",
      brand: "Fashion Brand",
      color: "Navy Blue",
      material: "Satin",
      gender: "Unisex",
      warranty: "No warranty",
      dimensions: "12 x 8 x 3 inches",
      weight: "300 grams"
    },
    { 
      image: "assets/images/p11.png", 
      name: "Kids Electric Car", 
      price: "$960", 
      actualPrice: "$1100", 
      star: 2, 
      totalRating: 458, 
      discount: '20%', 
      likedProduct: false,
      description: "Let your child explore the world in style with this fun and safe electric car. Perfect for outdoor adventures!",
      size: "Kids",
      brand: "Toy Brand",
      color: "Red",
      material: "Plastic",
      ageGroup: "3-8 years",
      maxWeight: "50 kg",
      batteryLife: "2 hours",
      dimensions: "50 x 30 x 25 inches",
      weight: "25 kg"
    },
    { 
        image: "assets/images/p7.png", 
        name: "CANON EOS DSLR Camera", 
        price: "$960", 
        star: 4, 
        totalRating: 458, 
        discount: 'Best',
        likedProduct: false,
        description: "Capture stunning photos and videos with the Canon EOS DSLR Camera. Perfect for enthusiasts and professionals.",
        resolution: "24.2 megapixels",
        sensorType: "APS-C CMOS",
        lensMount: "Canon EF-S",
        maxShutterSpeed: "1/4000 sec",
        dimensions: "5.3 x 3.9 x 3 inches",
        weight: "465 grams"
      },
      { 
        image: "assets/images/p8.png", 
        name: "ASUS FHD Gaming Laptop", 
        price: "$900", 
        star: 3, 
        totalRating: 350, 
        discount: 'New',
        likedProduct: false,
        description: "Experience immersive gaming with the ASUS FHD Gaming Laptop. Packed with high-performance hardware for smooth gameplay.",
        displaySize: "15.6 inches",
        processor: "Intel Core i7",
        graphicsCard: "NVIDIA GeForce GTX 1650",
        RAM: "16 GB DDR4",
        storage: "512 GB SSD",
        dimensions: "14.2 x 10.3 x 0.9 inches",
        weight: "2.3 kg"
      },
      { 
        image: "assets/images/p1.png", 
        name: "HAVIT HV-G92 Gamepad", 
        price: "$120", 
        actualPrice: "$160", 
        star: 4, 
        totalRating: 200, 
        discount: '40%', 
        likedProduct: false,
        description: "Enhance your gaming experience with the HAVIT HV-G92 Gamepad. Ergonomically designed for comfort and precision.",
        size: "Standard",
        connectivity: "Wired",
        compatibility: "Compatible with PC and PlayStation",
        warranty: "2-year warranty",
        dimensions: "6.4 x 4.4 x 2.4 inches",
        weight: "180 grams"
      },
      { 
        image: "assets/images/p2.png", 
        name: "AK-900 Wired Keyboard", 
        price: "$960", 
        actualPrice: "$1100", 
        star: 2, 
        totalRating: 458, 
        discount: '20%',
        likedProduct: false,
        description: "Upgrade your typing experience with the AK-900 Wired Keyboard. Featuring responsive keys and durable construction.",
        layout: "Full-size",
        keyType: "Mechanical",
        backlighting: "RGB",
        dimensions: "17.4 x 5.1 x 1.2 inches",
        weight: "1.2 kg"
      },
      { 
        image: "assets/images/p3.png", 
        name: "IPS LCD Gaming Monitor", 
        price: "$360", 
        actualPrice: "$490", 
        star: 3, 
        totalRating: 350, 
        discount: '35%',
        likedProduct: false,
        description: "Immerse yourself in the world of gaming with the IPS LCD Gaming Monitor. Featuring vibrant colors and smooth visuals.",
        screenSize: "24 inches",
        resolution: "1920 x 1080",
        refreshRate: "75 Hz",
        responseTime: "5 ms",
        dimensions: "21.9 x 8.3 x 15.8 inches",
        weight: "3.6 kg"
      },
      { 
        image: "assets/images/p4.png", 
        name: "S-Series Comfort Chair ", 
        price: "$375", 
        actualPrice: "$400", 
        star: 4, 
        totalRating: 99, 
        discount: '15%', 
        likedProduct: false,
        description: "Relax in style with the S-Series Comfort Chair. Designed for maximum comfort with a sleek and modern look.",
        material: "Leather",
        color: "Brown",
        maxWeightCapacity: "120 kg",
        dimensions: "25 x 25 x 42 inches",
        weight: "15 kg"
      },
      { 
        image: "assets/images/p12.png", 
        name: "RGB liquid CPU Cooler", 
        price: "$360", 
        actualPrice: "$490", 
        star: 3, 
        totalRating: 350, 
        discount: '35%',
        likedProduct: false,
        description: "Keep your CPU cool and stylish with the RGB Liquid CPU Cooler. Featuring efficient cooling performance and customizable RGB lighting.",
        compatibility: "Compatible with most CPU sockets",
        radiatorSize: "240mm",
        fanSpeed: "800 - 2000 RPM",
        noiseLevel: "20 - 30 dB",
        dimensions: "10 x 4.7 x 1.1 inches",
        weight: "800 grams"
      },
      { 
        image: "assets/images/p13.png", 
        name: "S-Series Comfort Chair ", 
        price: "$375", 
        actualPrice: "$400", 
        star: 4, 
        totalRating: 99, 
        discount: '15%', 
        likedProduct: false,
        description: "Experience unparalleled comfort with the S-Series Comfort Chair. Perfect for long hours of sitting whether at work or gaming.",
        material: "Fabric",
        color: "Gray",
        maxWeightCapacity: "150 kg",
        dimensions: "26 x 28 x 40 inches",
        weight: "18 kg"
      },
      { 
        image: "assets/images/p16.png", 
        name: "The north coat", 
        price: "$120", 
        actualPrice: "$160", 
        star: 1, 
        totalRating: 200, 
        discount: '40%', 
        likedProduct: false,
        description: "Stay warm and stylish with The North Coat. Perfect for chilly weather and outdoor adventures.",
        material: "Polyester",
        color: "Black",
        size: "Large",
        dimensions: "30 x 20 x 10 inches",
        weight: "1 kg"
      },
      { 
        image: "assets/images/p9.png", 
        name: "Jr. Zoom Soccer Cleats ", 
        price: "$375", 
        actualPrice: "$400", 
        star: 4, 
        totalRating: 99, 
        discount: 'Hot', 
        likedProduct: false,
        description: "Dominate the field with Jr. Zoom Soccer Cleats. Designed for speed and agility, these cleats are perfect for young soccer players.",
        size: "US 7",
        color: "Blue/Orange",
        material: "Synthetic",
        studsConfiguration: "Firm Ground (FG)",
        weight: "250 grams"
      },
  ];